# Generated by Django 3.2.4 on 2021-06-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(default='lixilei6028', max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(default='lixilei', max_length=128, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='端口名称')),
                ('phy', models.CharField(max_length=256, verbose_name='物理接口状态')),
                ('protocol', models.CharField(max_length=256, verbose_name='逻辑接口状态')),
                ('desc', models.CharField(max_length=256, verbose_name='端口描述')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='IP地址')),
            ],
            options={
                'unique_together': {('name', 'device')},
            },
        ),
    ]
