# Generated by Django 3.2.4 on 2021-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210630_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='role',
            field=models.CharField(default='SW', max_length=128, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(default='1.1.1.1', unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(default='FFFF-FFFF-FFFF', max_length=128, unique=True, verbose_name='sn'),
        ),
    ]
