# Generated by Django 3.2.4 on 2021-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210701_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='role',
            field=models.CharField(max_length=128, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(max_length=128, unique=True, verbose_name='sn'),
        ),
    ]
