# Generated by Django 3.2.4 on 2021-07-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210701_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.CharField(default=22, max_length=128, verbose_name='端口'),
        ),
    ]
