# Generated by Django 3.2.4 on 2021-07-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_ap_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='IP地址'),
        ),
    ]
