# Generated by Django 3.2.4 on 2021-07-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_alter_ap_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_version', models.CharField(max_length=128, verbose_name='产品版本')),
                ('uptime', models.CharField(max_length=128, verbose_name='更新时间')),
                ('vrp_version', models.CharField(max_length=128, verbose_name='虚拟版本')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='IP地址')),
            ],
        ),
    ]
