# Generated by Django 3.2.4 on 2021-07-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor_lldp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local_intf', models.CharField(max_length=128, verbose_name='本地接口')),
                ('Neighbor_dev', models.CharField(max_length=32, verbose_name='对端接口')),
                ('Neighbor_intf', models.CharField(max_length=128, verbose_name='对端接口')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.device', verbose_name='本地地址')),
            ],
        ),
    ]
