# Generated by Django 3.2.4 on 2021-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20210719_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tansceiver',
            name='connector',
            field=models.CharField(default='copper', max_length=128, verbose_name='连接类型'),
        ),
        migrations.AddField(
            model_name='tansceiver',
            name='vendor',
            field=models.CharField(default='copper', max_length=128, verbose_name='生产厂商'),
        ),
        migrations.AddField(
            model_name='tansceiver',
            name='wavelength',
            field=models.CharField(default='copper', max_length=128, verbose_name='波长'),
        ),
    ]
